/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BookStore;

/**
 *
 * @author RIAJUL
 */
public class DeliveryPr extends javax.swing.JFrame {

    /**
     * Creates new form DeliveryPr
     */
    public DeliveryPr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        BookStorePUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("BookStorePU").createEntityManager();
        deliverManQuery = java.beans.Beans.isDesignTime() ? null : BookStorePUEntityManager.createQuery("SELECT d FROM DeliverMan d");
        deliverManList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : deliverManQuery.getResultList();
        deliverManQuery1 = java.beans.Beans.isDesignTime() ? null : BookStorePUEntityManager.createQuery("SELECT d FROM DeliverMan d");
        deliverManList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : deliverManQuery1.getResultList();
        deliverManQuery2 = java.beans.Beans.isDesignTime() ? null : BookStorePUEntityManager.createQuery("SELECT d FROM DeliverMan d");
        deliverManList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : deliverManQuery2.getResultList();
        deliverManQuery3 = java.beans.Beans.isDesignTime() ? null : BookStorePUEntityManager.createQuery("SELECT d FROM DeliverMan d");
        deliverManList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : deliverManQuery3.getResultList();
        orderInfoQuery = java.beans.Beans.isDesignTime() ? null : BookStorePUEntityManager.createQuery("SELECT o FROM OrderInfo o");
        orderInfoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : orderInfoQuery.getResultList();
        deliverManQuery4 = java.beans.Beans.isDesignTime() ? null : BookStorePUEntityManager.createQuery("SELECT d FROM DeliverMan d");
        deliverManList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : deliverManQuery4.getResultList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, deliverManList4, jTable2);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${deliverManPK}"));
        columnBinding.setColumnName("Deliver Man PK");
        columnBinding.setColumnClass(BookStore.DeliverManPK.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryPr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryPr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryPr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryPr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryPr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager BookStorePUEntityManager;
    private java.util.List<BookStore.DeliverMan> deliverManList;
    private java.util.List<BookStore.DeliverMan> deliverManList1;
    private java.util.List<BookStore.DeliverMan> deliverManList2;
    private java.util.List<BookStore.DeliverMan> deliverManList3;
    private java.util.List<BookStore.DeliverMan> deliverManList4;
    private javax.persistence.Query deliverManQuery;
    private javax.persistence.Query deliverManQuery1;
    private javax.persistence.Query deliverManQuery2;
    private javax.persistence.Query deliverManQuery3;
    private javax.persistence.Query deliverManQuery4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private java.util.List<BookStore.OrderInfo> orderInfoList;
    private javax.persistence.Query orderInfoQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
